# Generated by Django 4.2 on 2023-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pr', 'Processing'), ('Co', 'Confirmed'), ('Ca', 'Canceled'), ('Dy', 'Delivery'), ('Dd', 'Delivered')], default='Pr', max_length=2),
        ),
    ]
